sudo: required

services:
  - docker

env:
  - BUILD_IMAGE="grundrausch3n/ergw-docker-base"

script:
  - docker build -t  $BUILD_IMAGE .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $BUILD_IMAGE
